config/routes.rb
Prelaunch::Application.routes.draw do
  
  resources :companies

  get '/' => 'pages#signup', :as => :signup
  get '/suggest' => 'companies#new', :as => :suggest
  get '/thanks' => 'pages#thanks', :as => :thanks

end

app/models/company.rb
class Company < ActiveRecord::Base
  
  external_url_regex = /(?i)\b((?:https?:\/\/|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?]))/
  
  validates :name, { :presence => true,
                     :uniqueness => { :case_sensitive => false },
                     :exclusion => { :in => %w[home contact about products product companies company login logout signup join register blog legal search feedback invite images image admin domesticated state states shop buy checkout cart],
                                     :message => "Name %{value} is taken." },
                     :length => { :in => 3..30 }} # replaced format of with a custom block
                     
  validates :external_url, {:presence => true,
                            :uniqueness => { :case_sensitive => false },
                            :format => { :with => external_url_regex },
                            :length => { :in => 4..300} }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to thanks_path
    else
      render "new"
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def signup
  end
  
  def thanks
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/companies/_errors.haml
- if @company.errors.any?
	#error_explanation
		Looks like there 
		- if @company.errors.count < 2
			was a problem.
		- else
			were some problems.
		- @company.errors.full_messages.each do |msg|
			%li
				= msg

app/views/companies/new.haml
.floater
.prelaunch2
	%span.din.heading.dark
		LIST NEW COMPANY
	.divider
	%p.din.gray.copy
		Listing your company on Domesticated gives the benefit of exposing your brand to a large, highly target audience, absolutely free.
		%br
		.divider
	= form_for @company do |f|
		= render 'errors', :object => f.object
		.field.din.full
			= f.text_field :name, :class => 'company-fields', :placeholder => 'Name'
		.field.din.full
			= f.text_field :external_url, :class => 'input_full', :placeholder => 'Website (optional)'
		= f.submit "suggest", :class => 'input-button din'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Domesticated | A better way to find products made in USA</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/signup.haml
.floater
.prelaunch
	
	= image_tag "logo.gif", :class => "logo"

	%p.din.gray.copy
		Looking for
		%span.dark
			Made in USA?
		Look no further.
	%br
	%p.din.gray.copy
		Domesticated is a new way to find products made in the USA. We’re still building our database, but we’ll let you know when we’re ready to launch.
	%br
	%form(action="http://tankjetstudios.us2.list-manage2.com/subscribe/post?u=f130e51d6887144eb949b6c50&amp;id=69be870032" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate email-form" target="_blank")
		%input(type="email" placeholder="Enter your email address." value="" name="EMAIL" class="email" id="email" placeholder="email address" required)
		%input(type="submit" value="keep me posted" name="subscribe" id="mc-embedded-subscribe" class="input-button din")
	%br
	.span.din.meantime.gray
		In the meantime, help us grow our database by 
		= link_to "adding a company.", suggest_path
	.divider
	%span.follow
		Follow us on
	%span.din.social
		= image_tag "twitter.gif", :class => "social-img"
		twitter
		= image_tag "facebook.gif", :class => "social-img"
		facebook

app/views/pages/thanks.haml
	%span.din.heading.dark
	Thanks for your suggestion!